### ISSUE TITLE
random generation of UUIDs in resource URIs

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#16]
UUIDs for resources URIs are generated randomly.

Should we try to generate them in a **deterministic** way?
E.g. I am thinking about a combination of source institution, filename, a progressive numeric id inside the file.

**Comment by pasqLisena** [comment]
sub-question:
How generate a deterministic UUID from a (string) parameter?

**Comment by rtroncy** [comment]
We should indeed not generate completely random UUIDs. The best is to SHA-1 a seed, this is what we do in 3cixty. More precisely, we use the following [piece of code](https://gist.github.com/giusepperizzo/630d32cc473069497ac1). The question, therefore, is what should we use as seed. Given that each record from each institution has probably an internal ID, I would suggest to use as see a concatenation of this ID + the database name to make sure our UUID will be unique. Thought?

**Comment by pasqLisena** [comment]
So, yes, each record has one identifier that is unique.
What do you mean with "the database name"? It is "bnf" and "pp" or maybe "data.doremus.org"?

Moreover, we must be sure that one record represent only 1 instance for each class. I think is true for Work, Expression, ... But what about Performance? How many performance are described in a record? we should check...

**Comment by rtroncy** [comment]
The uniqueness of the id is local to the database it comes from. By database name, I meant the exact 5 names we have in [this hierarchy](https://github.com/DOREMUS-ANR/knowledge-base/tree/master/data), there is 1 database from BnF, 1 from Philharmonie and 3 from Radio France.

Good question regarding the number of performances potentially described in a record. @marie-ototoi @pierrechoffe can you tell us?

Last remark; this is not a big problem if we happy to generate the same UUID SHA-1 string for two different DOREMUS classes.

**Comment by pasqLisena** [comment]
> Good question regarding the number of performances potentially described in a record.

Could be 0, 1 or 2 (i.e. the Premiere and the Création française).

**Comment by pierrechoffe** [comment]
>Could be 0, 1 or 2 (i.e. the Premiere and the Création française).

Yep !

**Comment by rtroncy** [comment]
No, we are talking in general. For any record (file) that an institution is providing, how many Work, Expression, Performance, etc. can be described. If we use the record ID to generate the DOREMUS UUID but if 2 different Performance are being described within the same record ID, we will get a collision of UUID. How is this problem solved in the source data if the same record ID refers to description of multiple objects of the same type?

**Comment by pierrechoffe** [comment]
Well this has to be checked in detail with each partner, but just talking about Premiere and Creation Française shows that there may be 2.
If we take an F24_Publication_Expression (described in a notice bibliographique) it could be linked with as many M43_Performed_Expression as there are works performed. Or just one if we create an F31_Performance (global performance) consisting of these M43. For example, a CD of the "12 greatest adagios" would contain 12 M43_Performed_Expression, or just one F31_Performance. The modelling is still very much in progress, so I think we could combine modelling thinking and implementation strategy, couldn't we?

**Comment by pasqLisena** [comment]
> If we take an F24_Publication_Expression (described in a notice bibliographique) it could be linked with as many M43_Performed_Expression as there are works performed.

Sure. But we have an identifier for each of them?if we have, the problem is solved.:)

> For example, a CD of the "12 greatest adagios" would contain 12 M43_Performed_Expression, or just one F31_Performance.

I don't like this second solution, we loose  a lot of granularity.

**Comment by pierrechoffe** [comment]
@pasqLisena In order to make things clearer, I created a graphic representation some time ago, you can find it here : https://drive.google.com/drive/folders/0B4s5dBwAmhJsfmZLN3dmVmxMLWxHXzRIcjVvWnJCYTh0cGtESDYxd2JqNmlDMjMzUEs4d1k
This is schema "Cto Vl Paganini & Spohr" it is based on the Variations3 example (on page 12 of : http://www.dlib.indiana.edu/projects/variations3/docs/v3FRBRreport.pdf)
We have 2 musical compositions performed for a recording. In our new schemas, we now have as many performances as we have works performed. This is independent from these works pre-existing before the performance or not, in other words if we have a series of 3 improvisations, there will be 3 performances - and in this case the performance plans will not incorporate an F22 Self-Contained Expression, because there is no such F22.
So for our 2 Violin Concertos, this means having 2 performing events.
The performance event is M42 and it creates at the same time a new Expression called M43 Performed Expression. In the schema, you can see 2 M42, creating 2 M43. If we had our "12 most beautiful adagios" recording, we would have 12 M42 and 12 M43.
In this schema, there is no global F31 Performance that would group all M42 together, so we have a very fine granularity.
Then I added various links between the M24 Tracks and the corresponding M43 (this basically says that these 3 Tracks are subdivisions of our Performed Expression), between the F24 Publication Expression and the corresponding 2 M43s (so this basically says that this album contains these Performed Expressions), and between our M43s and their corresponding F22s (this says that this Performed Expression incorporates somehow the original composition).
I sent you a message about this with questions regarding whether or not these links are useful and also whether it would be a good idea to create links that would be easily aligned with schema.org, I don't know if you ever saw this message.
If you need more info about the classes and properties, you can check the spreadsheet "nouvelles classes & propriétés" here : https://docs.google.com/spreadsheets/d/1RNhHnp4fWEhG8G4acx8FPi-nu9fUWNhc8JNf3SQwUFE/edit#gid=1401336326
Let me know what you think about the schema and if you see some way we can make it better :))

**Comment by pierrechoffe** [comment]
@pasqLisena This said, I reckon I did not answer your question precisely :) In order to be able to do so, we need to list all possible cases, including when our records are very poor. Sometimes you have details, with nice records and subrecords (notices et sous-notices), sometimes you just find horrible things because there was no money at the time to pay people to do the job. We need to check all the possible cases and how to deal with each. The schema above work when records contain enough information. If we have subrecords, I assume we can have an M42 with a unique identifier. When we don't have subrecords, it is more difficult but maybe we can find workarounds, like using the link to the initial composition ?

**Comment by rtroncy** [comment]
@pierrechoffe Indeed, you didn't reply to the original question ... you're discussing the modeling, while the original question is just about how things are identified in the source data so that we understand what basis we should take to generate the DOREMUS UUID. In order to progress, can you simply point us towards the source data that corresponds to the "Cto Vl Paganini & Spohr" example described in [your comment](https://github.com/DOREMUS-ANR/marc2rdf/issues/16#issuecomment-238088111)?

**Comment by pierrechoffe** [comment]
@rtroncy I cannot point towards the source data since this was not a BnF example, but I can point towards an equivalent one : http://catalogue.bnf.fr/ark:/12148/cb384428371.intermarc
This is a bibliographic record for an EMI recording of 2 Beethoven sonatas, among which our famous "moonlight sonata". You will see in 744$3 that there are links to the F22 that are being performed.
But there are no links to anything that resemble a performance (at least in Bnf records), the performance is a construction in the model. Therefore we should be able to assign one individual ID to each performance. 
As already mentioned, this is valid in optimal cases (which is a good example here), but things will get difficult in other cases, which we have to list.

**Comment by rtroncy** [comment]
Thanks for bringing a specific example, but here, we will not have the problem of creating colliding UUID, which is what this issue is all about. As you said, this record provide links to two different F22, so we will be able to create two different performance following the same pattern. Furthermore, this record is about a recording, something that is not yet worked on in the mapping table if I'm not missleaded.

**Comment by pasqLisena** [comment]
I am trying to write down what the UUID could be for each of the classes we currently instantiate on marc2rdf.

_N. occ._ is the number of occurrences in a single record.

Class | N. occ. | Parts for UUID
------------ | ------------- | -------------
F22_SelfContainedExpression | 1 | dbName + recordId + classCode
F28_ExpressionCreation | 1 | dbName + recordId + classCode
F14_IndividualWork | 1 | dbName + recordId + classCode
F15_ComplexWork | 1 | dbName + recordId + classCode
F42_RepresentativeExpressionAss... | 1 | dbName + recordId + classCode
F24_PublicationExpression | 0-1 | dbName + recordId + classCode
F30_PublicationEvent | 0-1 | dbName + recordId + classCode
F19_PublicationWork | 0-1 | dbName + recordId + classCode
F31_Performance | 0-2 | dbName + recordId + classCode + flag*
F25_PerformancePlan | 0-2 | dbName + recordId + classCode + flag*
F40_IdentifierAssignment | 1 | dbName + recordId** + classCode
F50_ControlledAccessPoint | 1 | dbName + recordId* + classCode

\* this flag could be 'p' for premiere and 'f' for French premiere.
\** for PP, there is one for the UNI100 and one for the TUM (see #17). In that cases we will generate 2 F40 /F50 couples, using respectively the recordId and the TUMid.

###  Why we put also the classCode?

Because in the future this URIs:
```
http://data.doremus.org/Complex_Work/F15/<UUID>
http://data.doremus.org/Individual_Work/F14/<UUID> 
```
could become 
```
http://data.doremus.org/work/<UUID>
http://data.doremus.org/work/<UUID> 
```
So, we need that the UUIDs are different.

**Comment by rtroncy** [comment]
This looks good, assuming that you ultimately SHA-1 the sum of parts for UUID to actually get the UUID.
