### ISSUE TITLE
Composer link

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#18]
In the mapping rules, the following line appears when we talk about the composer:

```
Conserver le contenu du $3 qui fait le lien vers la notice d'autorité
```

and the examples

```
# Philarmonie
UNI100:700$338954 $aBeethoven $bLudwig van $f1770-1827 
          > E82 = Beethoven, Ludwig van (1770-1827) [Identifiant : 38954]
UNI100:701$30051835 $aLennon $bJohn $f1940-1980 $4230
          > E82 = Lennon, John (1940-1980) [Identifiant : 0051835]

# BnF
100 $313891295 $w.0..b.....$aBeethoven$mLudwig van$d1770-1827
          > E82 = Beethoven, Ludwig van (1770-1827) 
```

Briefly, it is a numeric code.

We should find:
- [ ] How to save this information?
- [ ] How to use it (is it the parameter for getting the webpage of the artist)?

**Comment by rtroncy** [comment]
There are a lot of things that we need to slowly revisit when we implement the DOREMUS model (and in particular, the FRBRoo part) and the mappings rules need also to be re-worked a bit.

For this particular case, we should have, at the beginning, an instance of the ```F10 Person``` (equivalent to ```E21 Person```) class that will identify, for example, Ludwig van Beethoven. Such an instance is also of type ```E39 Actor``` and can have multiple ```E82 Appellation``` for which the definition reads:

> This class comprises any sort of name, number, code or symbol characteristically used to identify an E39 Actor. An E39 Actor will typically have more than one E82 Actor Appellation, and instances of E82 Actor Appellation in turn may have alternative representations. The distinction between corporate and personal names, which is particularly important in library applications, should be made by explicitly linking the E82 Actor Appellation to an instance of either E21 Person or E74 Group/E40 Legal Body. If this is not possible, the distinction can be made through the use of the P2 has type mechanism.

It seems to me that we should use labels (rdfs and/ skos) to represent the information contained in the ```E82 Appellation``` class. The identifier, e.g. 38954, is the unique ID for the Philharmonie that describes this person. If we have mint a DOREMUS URI from this ID for identifying this person, then we can just re-generate this URI and use it again as value for the property. In short, we should use the power of RDF links to magically relate the work with the person.

**Comment by pierrechoffe** [comment]
@pasqLisena we should also revisit the mapping rules with the latest of CRM/FRBRoo, in this case E82_Appellation will be deprecated. We will just keep the E41_Appellation and some (tbd) subclasses, such as E42_Identifier.
Is there any reason we should use F10_Person instead of E21_Person?
>we should use the power of RDF links to magically relate the work with the person.

@rtroncy aaaaah... at last the magic appeared :)))

**Comment by pasqLisena** [comment]
Answering to @pierrechoffe, actually we are using E21_Person.
And the person is directly connected by P131_is_identified_by to a string (so no class E82 is present).

```
ecrm:P14_carried_out_by  [
                a   ecrm:E21_Person ;
                ecrm:P131_is_identified_by  "Beethoven, Ludwig van(1770-1827)"
]
```

**Comment by pierrechoffe** [comment]
@pasqLisena sure, but p131_is_identified_by is a subclass of p1_is_identified_by with a specific range that is E82_Appellation so I assume that if E82_Appellation is deprecated so will p131, therefore it would be better to also change p131 for p1 in our mappings, right ?

**Comment by pasqLisena** [comment]
@pierrechoffe Yes, you are right.
P.S. where you can check the deprecation of a property/class?

**Comment by pierrechoffe** [comment]
deprecation might not be the right word since they will still be used by legacy implementations, it's now a recommendation (not to use E82_Appellation). You can find all the changes in the official documentation, the latest version is 6.2.1, the newest will be 6.2.2 with these latest changes. The "editorial notes" with all the amendments, version by version, actually make up half of the documentation :)

**Comment by pasqLisena** [comment]
Ok, I am going to change it so :)

**Comment by rtroncy** [comment]
Hold on, you didn't get my comments. First, it does not matter if we instantiate F10_Person or E21_Person since they are declared as ```owl:equivalentClass```, so an instance of one class is also an instance of the other. I agree to explicitly type those instances as ```rdf:type E21_Person```.

The bulk of my [previous comments](https://github.com/DOREMUS-ANR/marc2rdf/issues/18#issuecomment-237545883) is that we should use the built-in RDF properties when we can rather than re-inventing the wheel. RDFS has defined the ```rdfs:label``` property. SKOS has defined even more label properties (preferred, alternative, hidden, etc.). In this concrete case, why do you want to use the p131 or the p1 property if you have them already in RDFS or SKOS?

**Comment by pierrechoffe** [comment]
@pasqLisena **update**: discussions are still rolling regarding the narrowing of appellations to the sole E41_Appellation, so nothing is decided as yet and it will probably take time. But in the end I am pretty sure that E82 will be dropped, so to be on the safe side we should use E41.
Same thing with E50_date, we should not use it.

**Comment by rtroncy** [comment]
I disagree. We should not use E41 neither, see my [previous comment](https://github.com/DOREMUS-ANR/marc2rdf/issues/18#issuecomment-237615564)

**Comment by pierrechoffe** [comment]
>It seems to me that we should use labels (rdfs and/ skos) to represent the information contained in the E82 Appellation class. The identifier, e.g. 38954, is the unique ID for the Philharmonie that describes this person. If we have mint a DOREMUS URI from this ID for identifying this person, then we can just re-generate this URI and use it again as value for the property. In short, we should use the power of RDF links to magically relate the work with the person.

Can you give an example, so that I understand precisely what you mean ? I get the general point, but I miss the concrete implementation (and the possible discussion that may follow)

**Comment by rtroncy** [comment]
The example is provided in the [very first comment of this issue](https://github.com/DOREMUS-ANR/marc2rdf/issues/18#issue-169328040). For the Philharmonie, it is assumed that there is an instance of ```E21_Person``` which could have a DOREMUS UUID based on the 38954 identifier that could have plenty of labels (rdfs and skos), including ```Beethoven, Ludwig van (1770-1827)``` and many others (what you called E41).

Hence, when the  source data looks like:
```
# Philarmonie
UNI100:700$338954 $aBeethoven $bLudwig van $f1770-1827 
          > E82 = Beethoven, Ludwig van (1770-1827) [Identifiant : 38954]
```

we should NOT generate:
```
ecrm:P14_carried_out_by  [
   a   ecrm:E21_Person ;
   ecrm:P131_is_identified_by  "Beethoven, Ludwig van(1770-1827)"
]
```
which creates again and again an anonymous Person who has some labels via P131, but instead, we should generate:
```
ecrm:P14_carried_out_by  <http://data.doremus.org/person/38954> .
```

**Comment by pierrechoffe** [comment]
Ok, this is what I had understood (sometimes you make me feel intelligent) :))
Now, what if we have persons without identifiers? There will be thousands of them, especially when we describe Performances. Will we create Doremus identifiers for everyone ?

**Comment by rtroncy** [comment]
Yes, this is the ba-ba of RDF. If you want to re-use a resource, you MUST identify it, otherwise, this is leaf in a tree, a resource that would never be the subject of any triple (statement). Minting new URIs is cheap, it costs nothing. So this is not a problem to create too many identifiers, even though afterwards, we may (and probably will) reconcile them with other authoritative sources (VIAF, ISNI, etc.).

**Comment by pierrechoffe** [comment]
Or, to put it differently, when we have an identifier in the record, we use it. This way we do not use anonymous persons. When we do not have any identifier, (Mr Jean Dupond playing the triangle in the symphony) do we create one?
This, as I understand it, is a local identifier (here, this is just for PP). The same will be true for BnF and for RF. So in the end there will also be an alignment between institutions for Persons, right? And for all kinds of identified things for that matter, am I right?

**Comment by pierrechoffe** [comment]
cross messages :)

**Comment by rtroncy** [comment]
> Or, to put it differently, when we have an identifier in the record, we use it.

We use this source data identifier to mint (or build or create) the DOREMUS identifier (called UUID)

> When we do not have any identifier, (Mr Jean Dupond playing the triangle in the symphony) do we create one?

Yes.

> So in the end there will also be an alignment between institutions for Persons, right? And for all kinds of identified things for that matter, am I right?

Yes and yes.

**Comment by pasqLisena** [comment]
close because duplicate of #27
