### ISSUE TITLE
ISNI identifiers and mapping rules for authority records

### ISSUE THREAD

**Issue by manoach** [DOREMUS-ANR/marc2rdf#27]
Actually, we are assigning the composers on the form `"first name, last name (date of birth, date of death)" ` to the works (Exp: `Beethoven, Ludwig van(1770-1827)`). These information are found in the musical records. 

- [ ] We need to assign ISNI identifiers to the composers but the current DOREMUS model (to my knowledge) does not describe it: which property to which class can we assign the ISNI identifiers? 

- [ ] Do the rules for mapping authority records need to be defined? or do we only need to align those composers with ISNI knowledge base?

- If the rules are to be defined then URIs will be created as proposed by @rtroncy and @pasqLisena on the form : `<http://data.doremus.org/artist/UUID>` and I suggest that this is where it should be aligned with ISNI.

Below, two records of Ludwig van Beethoven to see what can be retrieved as information : 

1. From PP: [[here](https://drive.google.com/open?id=0B5aAYp6pCokXSElHbDYzOHlxNG8)]

2. From BNF: [[here](https://drive.google.com/open?id=0B5aAYp6pCokXM1d1akZOWTNIb0U)]

**Comment by rtroncy** [comment]
@manowb Can you please add a link to the original record you paste in the issue? And check the formatting of the XML content? I have tried to reformat already the one from BnF but the one from the Philharmonie has strange |.

There is no need to have a property for adding the ISNI identifier, since it identifies the Person (regardless of the exact type we will use). Check out the examples from @pasqLisena, there is already an example where an ISNI is used. Therefore, we have two possibilities:
* Either we mint a ```<http://data.doremus.org/artist/UUID>``` identifier that we link to the ISNI via a ```owl:sameAs```
* Or we directly use the ISNI identifier when instantiating the Person (the exact type needs to be decided)

**Comment by manowb** [comment]
@rtroncy thank you for your reply. I edited my post by adding the links to the records. So, I opt for the first possibility in the case where the person records from BNF and PP have to be processed and converted to RDF.

**Comment by pasqLisena** [comment]
> Check out the examples from @pasqLisena, there is already an example where an ISNI is used.

Yes, we use ISNI for the _Representative Expression Assignment_, normally made by BnF (so it is the BnF's ISNI):
http://data.doremus.org/event/a86a5fa5-741c-39ff-8192-7fe64efe969d

> Or we directly use the ISNI identifier when instantiating the Person (the exact type needs to be decided)

You mean that instead of `<http://data.doremus.org/artist/UUID>`, we will have `<http://www.isni.org/isni/ISNI_ID>` ? (When it is possible, because we should also consider missing matches).

We will have anyway `owl:sameAs` for linking to dbpedia, etc.

**Comment by pasqLisena** [comment]
> Do the rules for mapping authority records need to be defined? or do we only need to align those composers with ISNI knowledge base?

> the exact type needs to be decided

We should write an email to the modelling group for this, what do you think?

**Comment by manowb** [comment]
@pasqLisena Yes, I will do it :)

**Comment by rtroncy** [comment]
Let's be consistent ... and always mint a DOREMUS URI to identify our artists, and sameAs them afterwards with ISNI, DBpedia and other controlled vocabularies.

For generating the UUID, use the firstName + lastName + birthDate as seed.

For the model, let me propose it, the modeling group will generally have insufficient knowledge of the appropriate vocabularies to use

**Comment by manowb** [comment]
> always mint a DOREMUS URI to identify our artists, and sameAs them afterwards with ISNI

+1 I agree with you. we have to assign a DOREMUS URI --> We may not have enough metadata to unambiguously identify the person in the ISNI database and there may not be any ISNI for all persons.

> For the model, let me propose it, the modeling group will generally have insufficient knowledge of the appropriate vocabularies to use

I was about to send them an email. Okay, we let you propose it :)

**Comment by rtroncy** [comment]
Announced yesterday during the Semantic Web day organized by the MCC https://www.eventbrite.fr/e/billets-le-web-semantique-pour-les-donnees-culturelles-28689738781 ... European will soon mint as well their own ID for artists (while linking them to VIAF, ISNI, etc.) and aim to generate artist web page based on the data. See also the presentation of Cécile Devarenne from Europeana that will soon be online

**Comment by manoach** [comment]
Now, we have the URI pattern to identify the composers in the form of `<http://data.doremus.org/artist/UUID>` where the UUID is generated using the `firstName + lastName + birthDate` as seed. But how about the authority records coming from **_different institutions_** describing the _**same person**_? Must we consider the information about the source db as seed for generating the UUIDs?

**Comment by rtroncy** [comment]
This is a very good question. Basically, if we add the source in the seed, we will artificially generate different URIs for most likely similar artists for which we expect later on to be able to align and to reconcile. 

Regarding our current seed ```firstName + lastName + birthDate``` for generating the DOREMUS UUID, are we sure we will always have those 3 fields regardless of the data source in DOREMUS? If so, we can keep this strategy and the data about artist will be reconciled automatically across sources during the conversion time. If not, then what are the minimal information we will always get describing artists regardless of the source?

**Comment by pierrechoffe** [comment]
>Now, we have the URI pattern to identify the composers in the form of <http://data.doremus.org/artist/UUID> 

Is this pattern to be used for any person? We may have sound engineers, publishers, etc. who are not artists, so maybe "person" instead of "artist" would be more general?

**Comment by rtroncy** [comment]
No, we had already this conversation in earlier threads. What we want to cover is both individual and ensemble / group, and that's why "person" is not appropriate. In FOAF, there is an agent super type to abstract from person and group but "agent" is often misleading for average data consumers. That's why "artist" is a better term. This is the choice made by most of the LOD citizen (Europeana, BBC, Universal Music, Last.fm, etc.).

This pattern will not be used for any person, I don't think this is realistic, but it will be used for any remarkable person.

**Comment by manoach** [comment]
> Regarding our current seed firstName + lastName + birthDate for generating the DOREMUS UUID, are we sure we will always have those 3 fields regardless of the data source in DOREMUS?

Yes, we are.

> If so, we can keep this strategy and the data about artist will be reconciled automatically across sources during the conversion time.

Perfect, doing this, we will not have to align them later :) .... So, if it is OK, can I close the issue ?
