### ISSUE TITLE
[BnF] après + date

### ISSUE THREAD

**Issue by pasqLisena** [DOREMUS-ANR/marc2rdf#64]
Manage this case http://data.doremus.org/artist/612f6e35-e4b8-3551-9f3b-5f5728dc2dda

**Comment by pierrechoffe** [comment]
a date with ... means that there is uncertainty: 176. means "at some time between 1760 and 1769"
and 17.. means "at some time in the XVIII. century".
In some cases we can assert something, either because there are historical evidences or just because we know the person died let's say in 1799 and was not so old, so 17.. is a minimalistic assertion.

in *this* specific case (1...-après 1753), the problem is we don't know if we should write 17.. or 16.. for the birth date, so in my opinion this is equivalent to "unknown".

Do you already know how to treat the "après 1753" case?

**Comment by pasqLisena** [comment]
Answering @pierrechoffe :

### birth `1...`

I would write "1000" and set `ecrm:P79_beginning_is_qualified_by` as `"precision at millennium"`.
It means applying [the same rules we use for TimeSpan](https://github.com/DOREMUS-ANR/marc2rdf/blob/0c0fbaa94b0dd619d93513e7df6e4dd2cf165378/src/main/java/org/doremus/marc2rdf/main/TimeSpan.java#L106).

### death `après 1753`

I would write "1753" and set `ecrm:P81_end_is_qualified_by` as one of the following:
- `uncertain`, value already in use
- `not before` or `after`
